name: Generate index.html

on:
  push:
    paths:
      - "scripts/index.py"
  workflow_run:
    workflows: ["自动同步指定软件最新 Releases"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Generate index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/index.py

      - name: Commit index.html
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add index.html

          if ! git diff --staged --quiet; then
            git commit -m "Auto Update index.html"
            git push
          else
            echo "index.html 无变化，跳过提交"
          fi
